collections:
  authors:
    output: true

domain: ixolius.github.io
url: https://ixolius.github.io
repository: ixolius/ixolius.github.io

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
    values:
      layout: "default"
